# clipman
# Autogenerated from man page /usr/share/man/man1/clipman.1.gz
complete -c clipman -s h -l help -d 'Show context-sensitive help (also try --help-long and --help-man)'
complete -c clipman -l histpath -d 'Path of history file'
complete -c clipman -l primary -d 'Serve item to the primary clipboard.  Default: --no-primary'
complete -c clipman -l notify -d 'Send desktop notifications on errors'

