# fsearch
# Autogenerated from man page /usr/share/man/man1/fsearch.1.gz
complete -c fsearch -s h -l help -d 'Show help options'
complete -c fsearch -l help-all -d 'Show all help options . SS "Application Options"'
complete -c fsearch -l new-window -d 'Open a new application window'
complete -c fsearch -l preferences -d 'Show the application preferences'
complete -c fsearch -s s -l search -d 'Set the search pattern'
complete -c fsearch -s u -l update-database -d 'Update the database'
complete -c fsearch -s v -l version -d 'Print version information and exit'
complete -c fsearch -l display -d 'X display to use'

