# grimshot
# Autogenerated from man page /usr/share/man/man1/grimshot.1.gz
complete -c grimshot -l notify -d 'Show notifications to the user that a screenshot has been taken'
complete -c grimshot -l cursor -d 'Include cursors in the screenshot'
complete -c grimshot -l wait -d 'Wait for N seconds before taking a screenshot.  Waits after any'

