# grimblast
# Autogenerated from man page /usr/share/man/man1/grimblast.1.gz
complete -c grimblast -l notify -d 'Show notifications to the user that a screenshot has been taken'
complete -c grimblast -l cursor -d 'Include cursors in the screenshot'
complete -c grimblast -l freeze -d 'Freezes the screen before area selection'
complete -c grimblast -l wait -d 'Wait for N seconds before taking a screenshot.  Waits after any'
complete -c grimblast -l scale -d 'Passes the `-s` argument to `grim`'

