# gsmartcontrol-root
# Autogenerated from man page /usr/share/man/man1/gsmartcontrol-root.1.gz
complete -c gsmartcontrol-root -s '?' -l help -d 'Show help options'
complete -c gsmartcontrol-root -l help-all -d 'Show all help options'
complete -c gsmartcontrol-root -l help-gtk -d 'Show GTK+ options'
complete -c gsmartcontrol-root -l help-debug -d 'Show logging options . SS "Application Options:"'
complete -c gsmartcontrol-root -s l -l no-locale -d 'Don\'t use system locale'
complete -c gsmartcontrol-root -s V -l version -d 'Display version information'
complete -c gsmartcontrol-root -l no-scan -d 'Don\'t scan devices on startup'
complete -c gsmartcontrol-root -l no-hide-tabs -d 'Don\'t hide non-identity tabs when SMART is disabled.  Useful for debugging'
complete -c gsmartcontrol-root -l add-virtual -d 'Load smartctl data from file, creating a virtual drive'
complete -c gsmartcontrol-root -l add-device -d 'Add this device to device list'
complete -c gsmartcontrol-root -l display -d 'X display to use'
complete -c gsmartcontrol-root -s v -l verbose -d 'Enable verbose logging; same as --verbosity-level 5'
complete -c gsmartcontrol-root -s q -l quiet -d 'Disable logging; same as --verbosity-level 0'
complete -c gsmartcontrol-root -s b -l verbosity-level -d 'Set verbosity level [0-5]'

