# kanshi
# Autogenerated from man page /usr/share/man/man1/kanshi.1.gz
complete -c kanshi -s h -l help -d 'Show help message and quit'
complete -c kanshi -s c -l config -d 'Specifies a config file'
complete -c kanshi -s l -l listen-fd -d 'Listen on the specified file descriptor for IPC'

