# pacseek
# Autogenerated from man page /usr/share/man/man1/pacseek.1.gz
complete -c pacseek -s r -d 'Limit searching to a comma separated list of repositories'
complete -c pacseek -s s -d 'Search term when used with the  -r option'
complete -c pacseek -s a -d 'ASCII mode'
complete -c pacseek -s m -d 'Monochrome mode'
complete -c pacseek -s u -d 'Show upgrades after startup'
complete -c pacseek -s i -d 'Show installed packages after startup'
complete -c pacseek -s h -l help -d 'Display help and exit'

