# wpaperd
# Autogenerated from man page /usr/share/man/man1/wpaperd.1.gz
complete -c wpaperd -s n -l no-daemon -d 'Stay in foreground, do not detach'
complete -c wpaperd -l use-scaled-window -d 'Draw the wallpaper as a scaled window'
complete -c wpaperd -s h -l help -d 'Print help'
complete -c wpaperd -s V -l version -d 'Print version VERSION v0. 3. 0 AUTHORS Danilo Spinella <danilo. spinella@suse'

